
# GitHub Action for generating a contribution graph with a snake eating your contributions.
# Code plundered from https://dev.to/mishmanners/how-to-enable-github-actions-on-your-profile-readme-for-a-contribution-graph-4l66
name: Generate GitHub Contributions Snake Image

# Run every Sunday at 1am to generate an updated image.
on:
  schedule:
    - cron: "0 */6 * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Generate the snake images: https://github.com/marketplace/actions/generate-snake-game-from-github-contribution-grid
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: BilkoYevgen
          #gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Copy the generated image files to a branch to prevent it from cluttering up the main branch.
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: GitHubContributionsSnakeImage
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
